### ISSUE TITLE
Currently there is no support for git worktrees

### ISSUE THREAD

**Issue by michaelgeorgeattard** [alan-agius4/speedy-commit-msg-hook#15]
When a git worktree is added, a `.git` file is created, instead of a `.git` folder. 

Installations in a git worktree directory are currently exploding, as the file exists, however the `hooks` directory obviously does not.

My suggestions:
1. Either exit gracefully if `.git` is a file
2. Or support following directory inside `.git` file, and getting hooks from there.

**Comment by alan-agius4** [comment]
Thanks for reporting this, I’ll look at it in the coming days.
